### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Hey, just added support for Xcode 8 beta 1, Swift 3 preview 1. I've run the tests – all passed.

Cheers.

### CODE REVIEW

**Comment by czechboy0** [comment]
There will be changes needed in the `.travis.yml` file, as this code requires Xcode 8 and also swiftenv might need updating. We'll need changes like this to make CI pass: https://github.com/open-swift/C7/pull/46/files

**Comment by czechboy0** [comment]
Hmm I wonder, tests are still failing

**Comment by MaxDesiatov** [comment]
Turns out Swift 3 Preview 1 still has old NS prefixes in class names. The latest Swift builds on Swift CI already have that fixed. We can wait for Preview 2 release or just switch the Swift build used for this travis setup to those CI builds. Which of these do you think is the best?

**Comment by czechboy0** [comment]
Let's just wait.

**Comment by MaxDesiatov** [comment]
Swift 3 Preview 2 still has NS prefixes in Foundation class on Linux. It does look like that's going to be finally fixed in Preview 3, see https://github.com/apple/swift-corelibs-foundation/blob/swift-3.0-preview-3-branch/Foundation/NSTask.swift

**Pull request closed without merging**
